
name: crewdog_cv_lab
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  gradient_borders: ^1.0.0
  pin_code_fields: ^8.0.1
  flutter_lints: ^2.0.0
  dotted_border: ^2.1.0
  carousel_grid: ^1.0.5
  file_picker: ^6.1.1
  pdf: ^3.10.6
  printing: ^5.11.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  get: ^4.6.6
  image_picker: ^1.0.5
  get_storage: ^2.1.1
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.2.1
  speech_to_text: ^6.6.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/images/template/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Thin.ttf
          weight: 100
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-Black.ttf
          weight: 900
